"""event_type

Revision ID: 724bd8cc542a
Revises: 8b48fad30924
Create Date: 2026-09-01 18:15:01.136916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '724bd8cc542a'
down_revision: Union[str, Sequence[str], None] = '8b48fad30924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('event_type', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('direction', sa.String(), nullable=False))
    op.drop_column('transactions', 'transaction_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('transactions', 'direction')
    op.drop_column('transactions', 'event_type')
    # ### end Alembic commands ###
