"""Initial schema for production

Revision ID: 8b48fad30924
Revises: 
Create Date: 2026-09-01 04:35:40.828984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b48fad30924'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reason_code', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('previous_hash', sa.String(), nullable=False),
    sa.Column('current_hash', sa.String(), nullable=False),
    sa.Column('hmac_signature', sa.String(), nullable=False),
    sa.Column('nonce', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('current_hash')
    )
    op.create_index(op.f('ix_audit_events_event_id'), 'audit_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_audit_events_id'), 'audit_events', ['id'], unique=False)
    op.create_index(op.f('ix_audit_events_record_id'), 'audit_events', ['record_id'], unique=False)
    op.create_index(op.f('ix_audit_events_run_id'), 'audit_events', ['run_id'], unique=False)
    op.create_table('benchmark_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_size', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('precision', sa.Float(), nullable=False),
    sa.Column('recall', sa.Float(), nullable=False),
    sa.Column('match_rate', sa.Float(), nullable=False),
    sa.Column('processing_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benchmark_runs_id'), 'benchmark_runs', ['id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_entry_id'), 'journal_entries', ['entry_id'], unique=True)
    op.create_index(op.f('ix_journal_entries_id'), 'journal_entries', ['id'], unique=False)
    op.create_index(op.f('ix_journal_entries_reference'), 'journal_entries', ['reference'], unique=False)
    op.create_table('reconciliation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('auto_matched', sa.Integer(), nullable=True),
    sa.Column('manual_review', sa.Integer(), nullable=True),
    sa.Column('unresolved', sa.Integer(), nullable=True),
    sa.Column('match_rate', sa.Float(), nullable=True),
    sa.Column('reconciled_value_minor', sa.BigInteger(), nullable=True),
    sa.Column('processing_ms', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_runs_id'), 'reconciliation_runs', ['id'], unique=False)
    op.create_index(op.f('ix_reconciliation_runs_run_id'), 'reconciliation_runs', ['run_id'], unique=True)
    op.create_table('settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settlement_id', sa.String(), nullable=False),
    sa.Column('settlement_date', sa.DateTime(), nullable=False),
    sa.Column('gross_minor', sa.BigInteger(), nullable=True),
    sa.Column('fees_minor', sa.BigInteger(), nullable=True),
    sa.Column('tax_minor', sa.BigInteger(), nullable=True),
    sa.Column('adjustments_minor', sa.BigInteger(), nullable=True),
    sa.Column('net_minor', sa.BigInteger(), nullable=True),
    sa.Column('bank_credit_minor', sa.BigInteger(), nullable=True),
    sa.Column('variance_minor', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('utr', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlements_id'), 'settlements', ['id'], unique=False)
    op.create_index(op.f('ix_settlements_settlement_id'), 'settlements', ['settlement_id'], unique=True)
    op.create_index(op.f('ix_settlements_utr'), 'settlements', ['utr'], unique=False)
    op.create_table('source_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name')
    )
    op.create_index(op.f('ix_source_configs_id'), 'source_configs', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=False),
    sa.Column('source_reference', sa.String(), nullable=True),
    sa.Column('reference_core', sa.String(), nullable=True),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('settlement_id', sa.String(), nullable=True),
    sa.Column('utr', sa.String(), nullable=True),
    sa.Column('fee_minor', sa.BigInteger(), nullable=True),
    sa.Column('tax_minor', sa.BigInteger(), nullable=True),
    sa.Column('adjustment_minor', sa.BigInteger(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_canonical_id'), 'transactions', ['canonical_id'], unique=True)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_order_id'), 'transactions', ['order_id'], unique=False)
    op.create_index(op.f('ix_transactions_payment_id'), 'transactions', ['payment_id'], unique=False)
    op.create_index(op.f('ix_transactions_reference_core'), 'transactions', ['reference_core'], unique=False)
    op.create_index(op.f('ix_transactions_settlement_id'), 'transactions', ['settlement_id'], unique=False)
    op.create_index(op.f('ix_transactions_source'), 'transactions', ['source'], unique=False)
    op.create_index(op.f('ix_transactions_source_record_id'), 'transactions', ['source_record_id'], unique=False)
    op.create_index(op.f('ix_transactions_utr'), 'transactions', ['utr'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processing_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_event_id'), 'webhook_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_webhook_events_id'), 'webhook_events', ['id'], unique=False)
    op.create_table('exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exception_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('ai_explanation', sa.String(), nullable=True),
    sa.Column('recommended_action', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.run_id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.canonical_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exceptions_exception_id'), 'exceptions', ['exception_id'], unique=True)
    op.create_index(op.f('ix_exceptions_id'), 'exceptions', ['id'], unique=False)
    op.create_table('journal_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.String(), nullable=False),
    sa.Column('account', sa.String(), nullable=False),
    sa.Column('debit_minor', sa.BigInteger(), nullable=True),
    sa.Column('credit_minor', sa.BigInteger(), nullable=True),
    sa.Column('memo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.entry_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_lines_id'), 'journal_lines', ['id'], unique=False)
    op.create_table('match_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('left_transaction_id', sa.String(), nullable=False),
    sa.Column('right_transaction_id', sa.String(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['left_transaction_id'], ['transactions.canonical_id'], ),
    sa.ForeignKeyConstraint(['right_transaction_id'], ['transactions.canonical_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_candidates_id'), 'match_candidates', ['id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('left_transaction_id', sa.String(), nullable=False),
    sa.Column('right_transaction_id', sa.String(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['left_transaction_id'], ['transactions.canonical_id'], ),
    sa.ForeignKeyConstraint(['right_transaction_id'], ['transactions.canonical_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_table('explanation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exception_id', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.exception_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_explanation_requests_id'), 'explanation_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_explanation_requests_id'), table_name='explanation_requests')
    op.drop_table('explanation_requests')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_match_candidates_id'), table_name='match_candidates')
    op.drop_table('match_candidates')
    op.drop_index(op.f('ix_journal_lines_id'), table_name='journal_lines')
    op.drop_table('journal_lines')
    op.drop_index(op.f('ix_exceptions_id'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_exception_id'), table_name='exceptions')
    op.drop_table('exceptions')
    op.drop_index(op.f('ix_webhook_events_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_transactions_utr'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_source_record_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_source'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_settlement_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_reference_core'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_payment_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_order_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_canonical_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_source_configs_id'), table_name='source_configs')
    op.drop_table('source_configs')
    op.drop_index(op.f('ix_settlements_utr'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_settlement_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_id'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_reconciliation_runs_run_id'), table_name='reconciliation_runs')
    op.drop_index(op.f('ix_reconciliation_runs_id'), table_name='reconciliation_runs')
    op.drop_table('reconciliation_runs')
    op.drop_index(op.f('ix_journal_entries_reference'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_entry_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_benchmark_runs_id'), table_name='benchmark_runs')
    op.drop_table('benchmark_runs')
    op.drop_index(op.f('ix_audit_events_run_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_record_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
